#!/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(feature|bugfix)-.*$"

if ! [[ $BRANCH =~ $REGEX ]]; then
  echo "Your commit was rejected due to branching name"
  echo "Please rename your branch with '(feature|bugfix)-*' syntax"
  exit 1
fi

COMMITFORMAT="^([A-Z]+)-([0-9]+) (.*)$"

if ! grep -iqE "$COMMITFORMAT" "$1"; then
  echo "Your commit was rejected due to an invalid commit message."
  echo "The message should be of the format '[JIRA issue number] description', for example:"
  echo "  ABC-4321 example comment"
  exit 1
fi

