/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.repo

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    fun testedMethod(): String {
        return "Untested"
    }
}

fun main() {
    println(App().greeting)
}
